### ISSUE TITLE
Incorporate MANE transcripts for GRCh38

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#11]
**Is your feature request related to a problem? Please describe.**
Use [MANE](https://www.ncbi.nlm.nih.gov/refseq/MANE/) information for GRCh38 transcripts. As we don't support GRCh38 yet, this is for the future.

**Describe the solution you'd like**
Import the information, use the MANE transcripts for annotation where available. This will first require proper integration with Jannovar.

**Describe alternatives you've considered**
N/A

**Additional context**
- https://github.com/charite/jannovar/issues/546

**Comment by your-highness** [comment]
I don't know if this is so GRCh38 specific because most ENST are shared between GRCh37 and GRCh38 (especially if transcript version is ignored)

I would be a great asset to indicate a MANE transcript in the variant detail view with a little image or tag:
![image](https://user-images.githubusercontent.com/1949888/214852920-84b6a575-26cf-45f3-a781-d0a293bcac1f.png)

Happy to discuss here.

**Comment by holtgrewe** [comment]
Works in `main`.

![image](https://github.com/varfish-org/varfish-server/assets/521780/c45b6375-bbf2-413c-a4e6-ff4d894191f5)
