### ISSUE TITLE
Fix root cause for special result row set not updating when flags are updated

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#1378]
As described in #1375, we need to properly maintain the result set. Go through the API endpoints and ensure the following. Described for flags, but also applies for comments and acmg ratings.

- on creation of flag
    - ensure that an according entry exists in the result set
    - override the result set entry flag-related properties with flag, save
- on update of flag
    - ensure that an according entry exists in the result set
    - override the result set entry flag-related properties with flag, save
- on deletion of
    - fetch according entry of result set
    - check if there are any acmg annotations or comments
    - if this is not the case, delete the entry
    - otherwise, clear all flag-related properties and save the entry

**Comment by stolpeo** [comment]
RCA is not correct. The actual root cause it that the flags, comments and acmg ratings for a case were hold in the variant store and variants in the case result set were matched to the flags/comments/acmg ratings by release and coordinates. The matching was broken because `genomeBuild` was used instead of `release`.
