### ISSUE TITLE
Make ACMG-based assessment more configurable

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#477]
**Is your feature request related to a problem? Please describe.**
Grading using the ACMG criteria and scheme is very useful. As also mentioned in #476, specific groups and labs have made their own adjustments. Different schemes might be be used even at the same site, for example when used for ultra-rare vs. "just rare" vs. predisposition/risk grading. We need to cater to that.

**Describe the solution you'd like**
We keep the list of ACMG criteria fixed and also the list of categories we also keep the existing names.

We introduce an `AcmgBasedSchema` model (or similar) that captures the information which criteria goes into which category. For each such instance we also record a list of pairwise incompatible settings for simple sanity checking (aka "linting). We store a name and a version and also whether it is a "factory preset".

These schemas can be curated by a VarFish administrator only at the moment but assigned to projects by the project owner and to cases by contributors.

A migration creates an entry here that is named "ACMG 2015" in "version 1" and is a factory preset. All existing gradings are converted to use this.

Each case is annotated with which schema and version is used, each project defines the default grading schema. When a case is opened, users can adjust the ACMG based schema. In case of existing assessments, they get a preview of all graded variants and how changing the schema would change the assessment. They can either chose to apply the change (no way to revert right now), not apply the change and keep the schema constant, or clear all ACMG criteria assessments for now (with an additional confirmation).

We should also allow users to easily create a PDF document with the used settings that can be used/provided for documenting the assessment in one place and, e.g., be published on a website. Something like this is required for ClinVar submission anyway.

**Describe alternatives you've considered**
N/A

**Additional context**
- We explicitely aim for making ACMG based schemas more flexible. Supporting other schemas (such as ABC variant assessment) or allowing to add new items to the ACMG list is explicitely excluded for now and shall not be attempted.
- #202 
- Related but can be tackled afterwards: #476
- Refactoring the variant filtration front-end could simplify this but this issue can be tackled before: #474 
- Storing assessment per user and multiple assessments per variant is closely related but can be tackled independently, the main point here is that points are rendered in a different order and computation changes: #475

**Comment by xiamaz** [comment]
I will give some examples based on the ACGS Guidelines for ACMG Classification based on the 2019 and 2020 version.

# Variable weight of criteria

The **PVS1** criteria can be applied at either `very strong`, `strong` or `moderate` depending on variant type, location or evidence for the likelyhood of a null effect.

The **PS2** criteria can be applied from `supporting` up to `very strong` on a score based scale. 

![image](https://user-images.githubusercontent.com/3340720/166671296-a66929a4-e848-4a12-9094-5b87f436aa22.png)

The **PS4** criteria can be applied at `moderate` if the same variant has been identified in multiple affected unrelated individuals, or at `supporting` if only one.

**BS1** can be used as `standalone` for AD disorder with high penetrance.

# Valid combination of criteria

**PVS1** should not be used in combination with **PP3** or **PM4**. These are *mutually exclusive*.

**BP3** should not be used in combination with **BP3**

Some rules can be substituted with other rules if evidence is not sufficient. These are not mutually exclusive, but selection of both criteria might be a user error. An example is instead of *PS2*, *PM6* can be used if identity is assumed but not confirmed.

# Ruleset requirements

The previous examples have no claim to being comprehensive and should just serve as a point of reference for possible specifications in the ACGS guidelines.

From these an implementation for a ruleset should allow for:
- versioning
- valid range of weight for each criteria
- forbidden combinations of criteria
- possibly invalid combinations of criteria

Additionally it would be nice to have:
- hints for individual weights
- hints if forbidden combinations are used
- hints if combinations might make no sense (for example *PM6* might be used instead of *PS2*, but the combination is not forbidden if two lines of evidence do exist, in this scenario it would be great if the user could be notified that this might be a mistake)

**Comment by xiamaz** [comment]
The design document can be found and commented on here: https://docs.google.com/document/d/1pNZ5pO4iOl4AlfqsHmr4jgZoDNzPtxSg3c6lG8ddjJE/edit?usp=sharing

**Comment by xiamaz** [comment]
Additional caveat: ACGS Clingen Recommendation for PM2_sup, also proposes changes to calculation of ACMG severity grade. (https://www.clinicalgenome.org/site/assets/files/5182/pm2_-_svi_recommendation_-_approved_sept2020.pdf) 

A configuration design will need to make scoring rules configurable...
